In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
# for dirname, _, filenames in os.walk('/kaggle/input'):
#     for filename in filenames:
#         print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
! pip install pykeen

Requirement already satisfied: pykeen in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (1.11.0)
Requirement already satisfied: dataclasses-json in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from pykeen) (0.6.7)
Requirement already satisfied: numpy in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from pykeen) (1.26.4)
Requirement already satisfied: scipy>=1.7.0 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from pykeen) (1.11.4)
Requirement already satisfied: click in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from pykeen) (8.1.8)
Requirement already satisfied: click-default-group in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from pykeen) (1.2.4)
Requirement already satisfied: scikit-learn in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from pykeen) (1.3.2)
Requirement already satisfied: torch>=2.0 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from pykeen) (2.2.1+cu121)
Requirement already satisfied: tqdm in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from pykeen) (4.67.1)
Requirement already satisfied: requests in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from pykeen) (2.32.3)
Requirement already satisfied: optuna>=2.0.0 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from pykeen) (4.1.0)
Requirement already satisfied: pandas>=1.0.0 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from pykeen) (2.1.4)
Requirement already satisfied: tabulate in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from pykeen) (0.9.0)
Requirement already satisfied: more-click in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from pykeen) (0.1.2)
Requirement already satisfied: more-itertools in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from pykeen) (10.5.0)
Requirement already satisfied: pystow>=0.4.3 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from pykeen) (0.6.1)
Requirement already satisfied: docdata in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from pykeen) (0.0.4)
Requirement already satisfied: class-resolver>=0.5.1 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from pykeen) (0.5.4)
Requirement already satisfied: pyyaml in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from pykeen) (6.0.2)
Requirement already satisfied: torch-max-mem>=0.1.1 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from pykeen) (0.1.3)
Requirement already satisfied: torch-ppr>=0.0.7 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from pykeen) (0.0.8)
Requirement already satisfied: typing-extensions in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from pykeen) (4.12.2)
Requirement already satisfied: alembic>=1.5.0 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from optuna>=2.0.0->pykeen) (1.14.0)
Requirement already satisfied: colorlog in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from optuna>=2.0.0->pykeen) (6.9.0)
Requirement already satisfied: packaging>=20.0 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from optuna>=2.0.0->pykeen) (24.2)
Requirement already satisfied: sqlalchemy>=1.4.2 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from optuna>=2.0.0->pykeen) (2.0.37)
Requirement already satisfied: python-dateutil>=2.8.2 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from pandas>=1.0.0->pykeen) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from pandas>=1.0.0->pykeen) (2024.2)
Requirement already satisfied: tzdata>=2022.1 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from pandas>=1.0.0->pykeen) (2024.2)
Requirement already satisfied: filelock in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from torch>=2.0->pykeen) (3.16.1)
Requirement already satisfied: sympy in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from torch>=2.0->pykeen) (1.13.3)
Requirement already satisfied: networkx in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from torch>=2.0->pykeen) (3.4.2)
Requirement already satisfied: jinja2 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from torch>=2.0->pykeen) (3.1.5)
Requirement already satisfied: fsspec in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from torch>=2.0->pykeen) (2024.12.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.1.105 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from torch>=2.0->pykeen) (12.1.105)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.1.105 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from torch>=2.0->pykeen) (12.1.105)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.1.105 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from torch>=2.0->pykeen) (12.1.105)
Requirement already satisfied: nvidia-cudnn-cu12==8.9.2.26 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from torch>=2.0->pykeen) (8.9.2.26)
Requirement already satisfied: nvidia-cublas-cu12==12.1.3.1 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from torch>=2.0->pykeen) (12.1.3.1)
Requirement already satisfied: nvidia-cufft-cu12==11.0.2.54 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from torch>=2.0->pykeen) (11.0.2.54)
Requirement already satisfied: nvidia-curand-cu12==10.3.2.106 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from torch>=2.0->pykeen) (10.3.2.106)
Requirement already satisfied: nvidia-cusolver-cu12==11.4.5.107 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from torch>=2.0->pykeen) (11.4.5.107)
Requirement already satisfied: nvidia-cusparse-cu12==12.1.0.106 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from torch>=2.0->pykeen) (12.1.0.106)
Requirement already satisfied: nvidia-nccl-cu12==2.19.3 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from torch>=2.0->pykeen) (2.19.3)
Requirement already satisfied: nvidia-nvtx-cu12==12.1.105 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from torch>=2.0->pykeen) (12.1.105)
Requirement already satisfied: triton==2.2.0 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from torch>=2.0->pykeen) (2.2.0)
Requirement already satisfied: nvidia-nvjitlink-cu12 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from nvidia-cusolver-cu12==11.4.5.107->torch>=2.0->pykeen) (12.6.85)
Requirement already satisfied: marshmallow<4.0.0,>=3.18.0 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from dataclasses-json->pykeen) (3.25.0)
Requirement already satisfied: typing-inspect<1,>=0.4.0 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from dataclasses-json->pykeen) (0.9.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from requests->pykeen) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from requests->pykeen) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from requests->pykeen) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from requests->pykeen) (2024.12.14)
Requirement already satisfied: joblib>=1.1.1 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from scikit-learn->pykeen) (1.4.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from scikit-learn->pykeen) (3.5.0)
Requirement already satisfied: Mako in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from alembic>=1.5.0->optuna>=2.0.0->pykeen) (1.3.8)
Requirement already satisfied: six>=1.5 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas>=1.0.0->pykeen) (1.17.0)
Requirement already satisfied: greenlet!=0.4.17 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from sqlalchemy>=1.4.2->optuna>=2.0.0->pykeen) (3.1.1)
Requirement already satisfied: mypy-extensions>=0.3.0 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from typing-inspect<1,>=0.4.0->dataclasses-json->pykeen) (1.0.0)
Requirement already satisfied: MarkupSafe>=2.0 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from jinja2->torch>=2.0->pykeen) (3.0.2)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages (from sympy->torch>=2.0->pykeen) (1.3.0)

In [3]:
import torch

In [4]:
model = torch.load("./results/trained_model.pkl")
model

TransE(
  (loss): MarginRankingLoss(
    (margin_activation): ReLU()
  )
  (interaction): TransEInteraction()
  (entity_representations): ModuleList(
    (0): Embedding(
      (_embeddings): Embedding(83717, 50)
    )
  )
  (relation_representations): ModuleList(
    (0): Embedding(
      (_embeddings): Embedding(1024, 50)
    )
  )
  (weight_regularizers): ModuleList()
)

In [5]:
from pykeen.triples import TriplesFactory
triples_factory = TriplesFactory.from_path_binary("./results/training_triples/")
print(triples_factory.num_entities)  # Number of entities
print(triples_factory.num_relations)  # Number of relations

83717
1024

In [7]:
# triples_factory

TriplesFactory(num_entities=83717, num_relations=1024, create_inverse_triples=True, num_triples=98028, path="/teamspace/studios/this_studio/train.txt")

In [6]:
from pykeen.predict import predict_target
pred = predict_target(
    model = model,
    head="http://purl.obolibrary.org/obo/DOID_13099",
    relation="Parents",
    triples_factory = triples_factory.training
)

AttributeError: 'TriplesFactory' object has no attribute 'training'

In [ ]:
df = pred.df
df

       tail_id      score                                         tail_label
70163    70163  -3.635785          http://purl.obolibrary.org/obo/DOID_13099
26339    26339  -5.454598                                   Moyamoya disease
3954      3954  -5.499212  A cerebral arterial disease characterized by c...
69674    69674  -5.525541        http://purl.obolibrary.org/obo/DOID_0060184
70723    70723  -5.578431           http://purl.obolibrary.org/obo/DOID_3527
...        ...        ...                                                ...
14553    14553 -10.806461                                           DOID:169
50245    50245 -10.817248  ["Gamma-aminobutyric acid receptor subunit alp...
52462    52462 -10.817608                        ["Olfactory receptor 10G7"]
39183    39183 -10.817812                   SNOMEDCT_US_2016_03_01:195648002
44293    44293 -10.891389  The part of the intestine that lies between th...

[83717 rows x 3 columns]

In [ ]:
df.nlargest(n=10, columns="score")

       tail_id     score                                         tail_label
70163    70163 -3.635785          http://purl.obolibrary.org/obo/DOID_13099
26339    26339 -5.454598                                   Moyamoya disease
3954      3954 -5.499212  A cerebral arterial disease characterized by c...
69674    69674 -5.525541        http://purl.obolibrary.org/obo/DOID_0060184
70723    70723 -5.578431           http://purl.obolibrary.org/obo/DOID_3527
67566    67566 -5.680423         http://purl.obolibrary.org/obo/BTO_0000121
65436    65436 -5.683687                                   dto:DTO_61000008
70320    70320 -5.723330           http://purl.obolibrary.org/obo/DOID_1518
59189    59189 -5.736189                       bone marrow mononuclear cell
71344    71344 -5.756498           http://purl.obolibrary.org/obo/DOID_9275

In [ ]:
counter = 0
for i in df['tail_label']:
    if(i == 'http://purl.obolibrary.org/obo/DOID_3527'):
        break
    counter+=1
counter

4